In [1]:
import numpy as np

## Problem - 1: Array Creation

print("Problem 1: Array Creation Tasks")

# 1. Initialize an empty array with size 2x2.
empty_array = np.empty((2, 2))
print("1. Empty 2x2 Array (values are uninitialized):")
print(empty_array)

# 2. Initialize an all one array with size 4x2.
ones_array = np.ones((4, 2))
print("\n2. All One 4x2 Array:")
print(ones_array)

# 3. Return a new array of given shape and type, filled with a fill value (np.full).
full_array = np.full((3, 3), 42)
print("\n3. 3x3 Array filled with 42 (using np.full):")
print(full_array)

# Define a reference array for the next two tasks
ref_array = np.array([[10, 20], [30, 40]])

# 4. Return a new array of zeros with the same shape and type as a given array (np.zeros_like).
zeros_like_array = np.zeros_like(ref_array)
print("\n4. Zeros array with same shape as 'ref_array' (using np.zeros_like):")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array (np.ones_like).
ones_like_array = np.ones_like(ref_array)
print("\n5. Ones array with same shape as 'ref_array' (using np.ones_like):")
print(ones_like_array)

# 6. For an existing list new_list = [1,2,3,4] convert to a NumPy array (np.array()).
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\n6. Converted list to NumPy array:")
print(converted_array)
print(f"   Type of converted_array: {type(converted_array)}")

print("\n" + "="*50 + "\n")


Problem 1: Array Creation Tasks
1. Empty 2x2 Array (values are uninitialized):
[[3.90102411e-315 0.00000000e+000]
 [6.71024661e-310 6.71024661e-310]]

2. All One 4x2 Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. 3x3 Array filled with 42 (using np.full):
[[42 42 42]
 [42 42 42]
 [42 42 42]]

4. Zeros array with same shape as 'ref_array' (using np.zeros_like):
[[0 0]
 [0 0]]

5. Ones array with same shape as 'ref_array' (using np.ones_like):
[[1 1]
 [1 1]]

6. Converted list to NumPy array:
[1 2 3 4]
   Type of converted_array: <class 'numpy.ndarray'>




In [5]:
## Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

print("Problem 2: Array Manipulation Tasks")

# 1. Create an array with values ranging from 10 to 49 (np.arange).
range_array = np.arange(10, 50)
print("1. Array with values from 10 to 49:")
print(range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8 (np.reshape).
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values 0 to 8:")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix (np.eye).
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
array_mean = random_array.mean()
print("\n4. Random array (size 30, first 5 elements shown):")
print(random_array[:5])
print(f"   Mean of the array: {array_mean:.4f}")

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_matrix_10x10 = np.random.random((10, 10))
array_min = random_matrix_10x10.min()
array_max = random_matrix_10x10.max()
print

Problem 2: Array Manipulation Tasks
1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30, first 5 elements shown):
[0.49027953 0.21189502 0.81470914 0.54222846 0.85283112]
   Mean of the array: 0.4943


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [6]:
import numpy as np

## Problem - 3: Array Operations

print("Problem 3: Array Operations Tasks")

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(f"Defined arrays:\nx:\n{x}\ny:\n{y}\nv: {v}\nw: {w}\n")

# 1. Add the two array (x + y)
addition = x + y
print("1. Addition (x + y):")
print(addition)

# 2. Subtract the two array (y - x)
subtraction = y - x
print("\n2. Subtraction (y - x):")
print(subtraction)

# 3. Multiply the array with any integer (x * 10)
scalar_multiplication = x * 10
print("\n3. Scalar Multiplication (x * 10):")
print(scalar_multiplication)

# 4. Find the square of each element of the array (x^2)
square_elements = x**2
print("\n4. Square of each element in x (x**2):")
print(square_elements)

# 5. Find the dot product
print("\n5. Dot Products:")
dot_vw = np.dot(v, w)
print(f"   v and w (dot product): {dot_vw}")

# Dot product between x and v (matrix-vector multiplication)
dot_xv = np.dot(x, v)
print(f"   x and v (dot product/matrix-vector): {dot_xv}")

# Dot product between x and y (matrix multiplication)
dot_xy = np.dot(x, y)
print("   x and y (dot product/matrix multiplication):")
print(dot_xy)

# 6. Concatenate
print("\n6. Concatenation:")
concat_row = np.concatenate((x, y), axis=0)
print("   Concatenate x and y along row (axis=0 / vstack):")
print(concat_row)

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_col = np.concatenate((v_col, w_col), axis=1)
print("   Concatenate v and w along column (axis=1 / hstack):")
print(concat_col)

# 7. Concatenate x and v; observe and explain the error.
print("\n7. Concatenate x and v:")
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"   **Error Encountered:** {e}")
    print("\n   **Explanation:**")
    print("   The error 'all the input array dimensions except for the concatenation axis must match exactly' occurs because you are trying to concatenate a **2x2 matrix (x)** with a **1D array/vector of size 2 (v)** along `axis=0` (rows).")
    print("   For vertical stacking (`axis=0`), the number of columns (the non-concatenation axis) must be the same. `x` has 2 columns, but `v` is a 1D array, which NumPy treats as having no columns in this context unless explicitly reshaped. If `v` was reshaped to a 1x2 row vector, it would work.")

print("\n" + "="*50 + "\n")

Problem 3: Array Operations Tasks
Defined arrays:
x:
[[1 2]
 [3 5]]
y:
[[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]

1. Addition (x + y):
[[ 6  8]
 [10 13]]

2. Subtraction (y - x):
[[4 4]
 [4 3]]

3. Scalar Multiplication (x * 10):
[[10 20]
 [30 50]]

4. Square of each element in x (x**2):
[[ 1  4]
 [ 9 25]]

5. Dot Products:
   v and w (dot product): 219
   x and v (dot product/matrix-vector): [29 77]
   x and y (dot product/matrix multiplication):
[[19 22]
 [50 58]]

6. Concatenation:
   Concatenate x and y along row (axis=0 / vstack):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
   Concatenate v and w along column (axis=1 / hstack):
[[ 9 11]
 [10 12]]

7. Concatenate x and v:
   **Error Encountered:** all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

   **Explanation:**
   The error 'all the input array dimensions except for the concatenation axis must match exactly' occurs because you are trying to concatenat